name = "vox-quietus-backend"

account_id = "e47c223ef39af0490164800057ef846f"
workers_dev = true
compatibility_date = "2023-10-01"
main = "src/index.ts"
route = "scrivenly.com/api/*"

[vars]
PUBLIC_URL = "https://scrivenly.com/api"
FRONTEND_URL = "https://scrivenly.com"
SESKey = "AKIA36OXS3SM4YRL76M4"

[[r2_buckets]]
binding = "R2"
bucket_name = "vox-quietus-r2"
preview_bucket_name = "vox-quietus-r2"

[[d1_databases]]
binding = "D1"
database_name = "vox-quietus-d1"
database_id = "fbea1cb9-8a22-49c4-9c5f-d0e13c036f11"

[[durable_objects.bindings]]
name = "SUBMISSION_WEBSOCKET"
class_name = "SubmissionWebSocketServer"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SubmissionWebSocketServer"]

[observability]
enabled = true
head_sampling_rate = 1