name = "dancing-cats-backend"

account_id = "e47c223ef39af0490164800057ef846f"
workers_dev = true
compatibility_date = "2023-10-01"
main = "src/index.ts"
route = "api.dancingcats.org/*"

[vars]
PUBLIC_URL = "https://api.dancingcats.org"
FRONTEND_URL = "https://dancingcats.org"
SESKey = "AKIA36OXS3SM4YRL76M4"

[[r2_buckets]]
binding = "R2"
bucket_name = "dancing-cats-r2"
preview_bucket_name = "dancing-cats-r2"

[observability]
enabled = true
head_sampling_rate = 1