name = "dancing-cats-backend"

account_id = "e47c223ef39af0490164800057ef846f"
workers_dev = true
compatibility_date = "2023-10-01"
main = "src/index.ts"
route = "api.dancingcats.org/*"

[[r2_buckets]]
binding = "R2"
bucket_name = "dancing-cats-r2"
preview_bucket_name = "dancing-cats-r2"